version: '3'

services:
    db:
        image: 'postgres:13'
        container_name: 'java-postgres'
        ports:
            - 15432:5432
        environment:
            - 'POSTGRES_USER=sa'
            - 'POSTGRES_HOST_AUTH_METHOD=trust'
            - 'POSTGRES_DB=java'
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
